export const DUMMY_POKEMONS = [

    {
        id: 'p1',
        name: 'Charmander',
        avatar: 'assets/pokemons/Charmander.png',
        gif: 'assets/pokemons/Charmander-gif.gif',
        attack: 80,
        defense: 60,
        energy: 'assets/images/fire.png',
        secondEvolution: 'Charmeleon',
        secondGif: 'assets/pokemons/Charmeleon-gif.gif',
        secondAvatar: 'assets/pokemons/Charmeleon.png',
        secondAttack: 490,
        secondDefense: 570,
        thirdEvolution: 'Charizard',
        thirdGif: 'assets/pokemons/Charizard-gif.gif',
        thirdAvatar: 'assets/pokemons/Charizard.png',
        thirdAttack: 810,
        thirdDefense: 980,
    },
    {
        id: 'p2',
        name: 'Bulbasaur',
        avatar: 'assets/pokemons/Bulbasaur.png',
        gif: 'assets/pokemons/Bulbasaur-gif.gif',
        attack: 70,
        defense: 65,
        energy: 'assets/images/grass.png',
        secondEvolution: 'Ivysaur',
        secondGif: 'assets/pokemons/Ivysaur-gif.gif',
        secondAvatar: 'assets/pokemons/Ivysaur.png',
        secondAttack: 585,
        secondDefense: 475,
        thirdEvolution: 'Venusaur',
        thirdGif: 'assets/pokemons/Venusaur-gif.gif',
        thirdAvatar: 'assets/pokemons/Venusaur.png',
        thirdAttack: 910,
        thirdDefense: 890,
    },
    {
        id: 'p3',
        name: 'Squirtle',
        avatar: 'assets/pokemons/Squirtle.png',
        gif: 'assets/pokemons/Squirtle-gif.gif',
        attack: 65,
        defense: 80,
        energy: 'assets/images/water.png',
        secondEvolution: 'Wartortle',
        secondGif: 'assets/pokemons/Wartortle-gif.gif',
        secondAvatar: 'assets/pokemons/Wartortle.png',
        secondAttack: 475,
        secondDefense: 685,
        thirdEvolution: 'Blastoise',
        thirdGif: 'assets/pokemons/Blastoise-gif.gif',
        thirdAvatar: 'assets/pokemons/Blastoise.png',
        thirdAttack: 895,
        thirdDefense: 928,
    },
    {
        id: 'p4',
        name: 'Dratini',
        avatar: 'assets/pokemons/Dratini.png',
        gif: 'assets/pokemons/Dratini-gif.gif',
        attack: 90,
        defense: 85,
        energy: 'assets/images/air.png',
        secondEvolution: 'Dragonair',
        secondGif: 'assets/pokemons/Dragonair-gif.gif',
        secondAvatar: 'assets/pokemons/Dragonair.png',
        secondAttack: 520,
        secondDefense: 690,
        thirdEvolution: 'Dragonite',
        thirdGif: 'assets/pokemons/Dragonite-gif.gif',
        thirdAvatar: 'assets/pokemons/Dragonite.png',
        thirdAttack: 990,
        thirdDefense: 976,
    },
    {
        id: 'p5',
        name: 'Magikarp',
        avatar: 'assets/pokemons/Magikarp.png',
        gif: 'assets/pokemons/Magikarp-gif.gif',
        attack: 10,
        defense: 55,
        energy: 'assets/images/water.png',
        secondEvolution: 'Gyarados',
        secondGif: 'assets/pokemons/Gyarados-gif.gif',
        secondAvatar: 'assets/pokemons/Gyarados.png',
        secondAttack: 725,
        secondDefense: 880,
    },
    {
        id: 'p6',
        name: 'Ekans',
        avatar: 'assets/pokemons/Ekans.png',
        gif: 'assets/pokemons/Ekans-gif.gif',
        attack: 60,
        defense: 44,
        energy: 'assets/images/snake.png',
        secondEvolution: 'Arbok',
        secondGif: 'assets/pokemons/Arbok-gif.gif',
        secondAvatar: 'assets/pokemons/Arbok.png',
        secondAttack: 685,
        secondDefense: 760,
    },
    {
        id: 'p7',
        name: 'Chikorita',
        avatar: 'assets/pokemons/Chikorita.png',
        gif: 'assets/pokemons/Chikorita-gif.gif',
        attack: 55,
        defense: 65,
        energy: 'assets/images/grass.png',
        secondEvolution: 'Bayleef',
        secondGif: 'assets/pokemons/Bayleef-gif.gif',
        secondAvatar: 'assets/pokemons/Bayleef.png',
        secondAttack: 570,
        secondDefense: 675,
        thirdEvolution: 'Meganium',
        thirdGif: 'assets/pokemons/Meganium-gif.gif',
        thirdAvatar: 'assets/pokemons/Meganium.png',
        thirdAttack: 890,
        thirdDefense: 940,
    },
    {
        id: 'p8',
        name: 'Weedle',
        avatar: 'assets/pokemons/Weedle.png',
        gif: 'assets/pokemons/Weedle-gif.gif',
        attack: 35,
        defense: 30,
        energy: 'assets/images/grass.png',
        secondEvolution: 'Kakuna',
        secondGif: 'assets/pokemons/Kakuna-gif.gif',
        secondAvatar: 'assets/pokemons/Kakuna.png',
        secondAttack: 245,
        secondDefense: 755,
        thirdEvolution: 'Beedrill',
        thirdGif: 'assets/pokemons/Beedrill-gif.gif',
        thirdAvatar: 'assets/pokemons/Beedrill.png',
        thirdAttack: 820,
        thirdDefense: 860,
    },
    {
        id: 'p9',
        name: 'Gastly',
        avatar: 'assets/pokemons/Gastly.png',
        gif: 'assets/pokemons/Gastly-gif.gif',
        attack: 80,
        defense: 50,
        energy: 'assets/images/psychic.png',
        secondEvolution: 'Haunter',
        secondGif: 'assets/pokemons/Haunter-gif.gif',
        secondAvatar: 'assets/pokemons/Haunter.png',
        secondAttack: 595,
        secondDefense: 755,
        thirdEvolution: 'Gengar',
        thirdGif: 'assets/pokemons/Gengar-gif.gif',
        thirdAvatar: 'assets/pokemons/Gengar.png',
        thirdAttack: 720,
        thirdDefense: 760,
    },
    {
        id: 'p10',
        name: 'Abra',
        avatar: 'assets/pokemons/Abra.png',
        gif: 'assets/pokemons/Abra-gif.gif',
        attack: 205,
        defense: 355,
        energy: 'assets/images/psychic.png',
        secondEvolution: 'Kadabra',
        secondGif: 'assets/pokemons/Kadabra-gif.gif',
        secondAvatar: 'assets/pokemons/Kadabra.png',
        secondAttack: 605,
        secondDefense: 660,
        thirdEvolution: 'Alakazam',
        thirdGif: 'assets/pokemons/Alakazam-gif.gif',
        thirdAvatar: 'assets/pokemons/Alakazam.png',
        thirdAttack: 825,
        thirdDefense: 905,
    },
    {
        id: 'p11',
        name: 'Ho-Oh',
        avatar: 'assets/pokemons/Ho-Oh.png',
        gif: 'assets/pokemons/Ho-Oh-gif.gif',
        attack: 988,
        defense: 967,
        energy: 'assets/images/fire.png',
        secondEvolution: 'Shiny Ho-Oh',
        secondGif: 'assets/pokemons/Shiny-Ho-Oh-Gif.gif',
        secondAvatar: 'assets/pokemons/Shiny-Ho-Oh.png',
        secondAttack: 990,
        secondDefense: 985,
    },
    {
        id: 'p12',
        name: 'Lugia',
        avatar: 'assets/pokemons/Lugia.png',
        gif: 'assets/pokemons/Lugia-gif.gif',
        attack: 985,
        defense: 930,
        energy: 'assets/images/air2.png',
        secondEvolution: 'Shiny Lugia',
        secondGif: 'assets/pokemons/Shiny-Lugia-gif.gif',
        secondAvatar: 'assets/pokemons/Shiny-Lugia.png',
        secondAttack: 995,
        secondDefense: 990,
    },
    {
        id: 'p13',
        name: 'Mew',
        avatar: 'assets/pokemons/Mew.png',
        gif: 'assets/pokemons/Mew-gif.gif',
        attack: 995,
        defense: 990,
        energy: 'assets/images/psychic-air.png',
        secondEvolution: 'Shiny Mew',
        secondGif: 'assets/pokemons/Shiny-Mew-gif.gif',
        secondAvatar: 'assets/pokemons/Shiny-Mew.png',
        secondAttack: 999,
        secondDefense: 999,
    },
    {
        id: 'p14',
        name: 'Mewtwo',
        avatar: 'assets/pokemons/Mewtwo.png',
        gif: 'assets/pokemons/Mewtwo-gif.gif',
        attack: 990,
        defense: 985,
        energy: 'assets/images/psychic-air.png',
        secondEvolution: 'Shiny Mewtwo',
        secondGif: 'assets/pokemons/Shiny-Mewtwo-gif.gif',
        secondAvatar: 'assets/pokemons/Shiny-Mewtwo.png',
        secondAttack: 997,
        secondDefense: 999,
    },
];

